//! Shared fixtures for the fuzz targets: deterministic keys (so a seed corpus generated by
//! `cargo run -p vpqc --example gen_fuzz_corpus` matches) and a tiny input splitter.

use std::sync::OnceLock;

use vpqc::{KeyPair, Profile};
use vpqc_core::testing::FixedRandom;

/// Deterministic encryption key pair per profile (seed byte 0x11 + profile id).
pub fn enc_keys() -> &'static [KeyPair] {
    static K: OnceLock<Vec<KeyPair>> = OnceLock::new();
    K.get_or_init(|| {
        Profile::ALL
            .iter()
            .map(|p| vpqc::encryption::generate_with(*p, &mut FixedRandom::new(&[0x11 + p.to_u8(); 64])).unwrap())
            .collect()
    })
}

/// Deterministic signing key pair per profile (seed byte 0x21 + profile id).
pub fn sig_keys() -> &'static [KeyPair] {
    static K: OnceLock<Vec<KeyPair>> = OnceLock::new();
    K.get_or_init(|| {
        Profile::ALL
            .iter()
            .map(|p| vpqc::signing::generate_with(*p, &mut FixedRandom::new(&[0x21 + p.to_u8(); 64])).unwrap())
            .collect()
    })
}

/// Deterministic JOSE signing keys: ML-DSA-65 (seed 0x31) and ML-DSA-87 (seed 0x32).
pub fn jose_keys() -> &'static [vpqc_jose::SigningKey] {
    use vpqc_jose::{Algorithm, SigningKey};
    static K: OnceLock<Vec<SigningKey>> = OnceLock::new();
    K.get_or_init(|| {
        vec![
            SigningKey::from_seed(Algorithm::MlDsa65, &[0x31; 32]),
            SigningKey::from_seed(Algorithm::MlDsa87, &[0x32; 32]),
        ]
    })
}

/// A fixed ML-DSA root (seed 0x41) and a leaf it issued (seed 0x42), created once per process.
pub fn x509_pki() -> &'static (vpqc_x509::Certificate, vpqc_x509::Certificate) {
    use vpqc_x509::{Algorithm, CertificateParams, PrivateKey};
    static P: OnceLock<(vpqc_x509::Certificate, vpqc_x509::Certificate)> = OnceLock::new();
    P.get_or_init(|| {
        let root_key = PrivateKey::from_seed(Algorithm::MlDsa65, &[0x41; 32]);
        let root = CertificateParams::ca("Fuzz Root", 3650).self_signed(&root_key).unwrap();
        let leaf_key = PrivateKey::from_seed(Algorithm::MlDsa65, &[0x42; 32]);
        let leaf = CertificateParams::end_entity("fuzz", 3650)
            .dns_names(&["fuzz.example"])
            .issue(leaf_key.public_key(), &root, &root_key)
            .unwrap();
        (root, leaf)
    })
}

/// Consumes bytes from the front of the fuzz input.
pub struct Input<'a>(pub &'a [u8]);

impl<'a> Input<'a> {
    /// One byte (0 when exhausted).
    pub fn byte(&mut self) -> u8 {
        match self.0.split_first() {
            Some((b, rest)) => {
                self.0 = rest;
                *b
            }
            None => 0,
        }
    }

    /// A length-prefixed slice (length byte, capped by what remains).
    pub fn slice(&mut self) -> &'a [u8] {
        let n = (self.byte() as usize).min(self.0.len());
        let (a, b) = self.0.split_at(n);
        self.0 = b;
        a
    }

    /// Everything that remains.
    pub fn rest(self) -> &'a [u8] {
        self.0
    }
}
